# Site Settings
url: https://homedm.eim.world # the base hostname & protocol for your site, e.g. https://example.com

theme: jekyll-theme-dinky
encoding: utf-8

# Build settings
exclude: ['Gemfile', 'Gemfile.lock', 'vendor']

# Site Author
author:
    name: homedm
    avatar: black_cat_icon.png
    email: email@example.com
    description: ># このページは@homedmのユーザーページです。

twitter_username: retasutomato
github_username: homedm
