# Site Settings
# the base hostname & protocol for your site, e.g. https://example.com
url: https://homedm.eim.world
title: tomato diary
description: this page is personal home page.


theme: jekyll-theme-dinky
encoding: utf-8

# Build settings
exclude: ['Gemfile', 'Gemfile.lock', 'vendor', '.textlintrc', 'node_modules/', 'package-lock.json', 'package.json' ]
plugins:
    - "jekyll-github-metadata"

# Site Author
author:
    name: homedm
    avatar: black_cat_icon.png
    email: email@example.com

twitter_username: retasutomato
github_username: homedm
